name: Node CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node ENV
        uses: actions/setup-node@2.1.5
        with:
          node-version: 18
          check-latest: true

      - name: Install depedencies
        run: pnpm i

      - name: Running Unit Testing
        run: pnpm test