name: Node CD
on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node ENV
        uses: actions/setup-node@v4
        with:
          node-version: 18
          check-latest: true

      - name: Install depedencies
        run: pnpm install

      - name: Running Unit Testing
        run: pnpm test

      - name: Deploy using ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/apps/CICD
            git pull origin main
            git status
            pnpm install --only=prod
            pm2 restart testingApp